version: "3.7"

services:
  redis:
    container_name: covid-api-redis-test
    volumes:
      - redis-data-test:/data

  app:
    command: ["npm", "test-single", "$(cat test_to_run.txt)"]
    build: .
    environment:
      - TEST_MODE=true
      - DOCKER=true
    container_name: covid-api-app-test

volumes:
  redis-data-test:
