version: '3.7'
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "yourpassword"]
    hostname: redis
    networks:
      - redis-net
    ports:
      - 6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - redis-net
    depends_on:
      - redis

networks:
  redis-net:
