version: "3.7"

services:
  redis:
    container_name: covid-api-redis-test
    volumes:
      - redis-data-test:/data
  scraper:
    build: .
    image: covidapi-scraper
    container_name: covid-api-scraper
    command: ["npm", "run", "start:scraper"]
    restart: always
    environment:
      - TEST_MODE=true
      - DOCKER=true
    networks:
      - redis-net
    depends_on:
      - redis
  app:
    command: ["npm", "test"]
    build: .
    environment:
      - TEST_MODE=true
      - DOCKER=true
    container_name: covid-api-app-test

volumes:
  redis-data-test: