--- 
apiVersion: v1
kind: Namespace
metadata:
  name: novelcovid-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: novelcovid-api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: novelcovid/api:8e607d1
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /all
            port: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: novelcovid-api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 3000
    targetPort: 3000


#--- 
#apiVersion: v1
#kind: ConfigMap
#metadata:
  #name: api-configmap
#data:
  #key: value
