name: Example
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: touch touched_files.txt
      - run: for changed_file in ${{ steps.files.outputs.all }}; do echo -n ${changed_file} >> touched_files.txt; done
      - run: cat touched_files.txt
      - run: node argv.js ${{ steps.files.outputs.all }}
      - run: echo $(ls)