name: Example
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      # get changed files
      - id: files
        uses: jitterbit/get-changed-files@v1
      # create file to hold tests to run
      - run: touch test_to_run.txt
      # run node script mapping changed files to tests
      - run: node argv.js ${{ steps.files.outputs.all }} >> test_to_run.txt
      - run: cat test_to_run.txt