name: Example

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - run: echo -n -e "HELLO\n !\n World!" > text.txt

    - uses: pCYSl5EDgo/cat@master
      id: hello
      with:
        path: text.txt

    - run: echo $(ls)
      env:
        TEXT: ${{ steps.hello.outputs.text }}