name: Example
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1

      - run: touch text.txt
      
      - run: for changed_file in ${{ steps.files.outputs.all }}; do echo "${changed_file}"" >> text.txt; done

      - uses: actions/checkout@v2

      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: text.txt

      # - run: echo $(ls)
      #   env:
      #     TEXT: ${{ steps.hello.outputs.text }}