name: Example

on: push

jobs:
	test-job:
		runs-on: ubuntu-latest
		steps:
      - uses: jitterbit/get-changed-files@v1
        id: files
      
      - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
        echo "Do something with this ${changed_file}."
        done

      - uses: actions/checkout@v2

      - run: echo -n -e "HELLO\n !\n World!" > text.txt

      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: text.txt

      - run: echo $(ls)
        env:
          TEXT: ${{ steps.hello.outputs.text }}